name = "SMCsamplers"
uuid = "2328efba-24c2-4a10-a32f-a74f69d05fca"
version = "1.0.0-DEV"
authors = ["Mattias Villani"]

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LineSearches = "d3d80556-e9d4-5f37-9878-2ab0fcc64255"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
Measures = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
PDMats = "90014a1f-27ba-587c-ab20-58faa44d9150"
PProf = "e4faabce-9ead-11e9-39d9-4379958e3056"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Profile = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Utils = "a6a4a4df-ba9f-45e9-bafc-bec3296762b9"

[compat]
BenchmarkTools = "1.6.0"
CSV = "0.10.15"
Distributions = "0.25.113"
ForwardDiff = "1.0.1"
LaTeXStrings = "1.4.0"
LineSearches = "7.4.0"
LinearAlgebra = "1.11.0"
Literate = "2.20.1"
Measures = "0.3.2"
Optim = "1.13.3"
PDMats = "0.11.31"
PProf = "3.2.0"
Plots = "1.40.9"
Profile = "1.11.0"
Random = "1.11.0"
Revise = "3.8.1"
Statistics = "1.11.1"
Utils = "0.1.0"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
